### ISSUE TITLE
Cron job not running

### ISSUE THREAD

**Issue by sfmarques** [owncloud-docker/server#50] opened 2018-04-18 17:38 UTC
Cron job not runing

![image](https://user-images.githubusercontent.com/5604227/38948443-8ace2270-4337-11e8-8f41-acdd7553d374.png)

crontab -u www-data -e

![image](https://user-images.githubusercontent.com/5604227/38948469-a26be3f4-4337-11e8-9304-c901ab8b5238.png)

ownCloud Version 10.0.7.2

Thanks

**Comment by voroyam** [comment] 2018-04-23 11:14
Can you check if running this on startup solves your issue?

```
test -f /etc/cron.d/owncloud && touch /etc/cron.d/owncloud
test -f /etc/cron.d/php && touch /etc/cron.d/php
```

**Comment by tboerger** [comment] 2018-04-23 11:33
I'm currently refactoring the build process of the containers, I will come back top this issue soon.

**Comment by tboerger** [comment] 2018-04-25 07:54
Duplicate of https://github.com/owncloud-docker/base/issues/14

**Closed by tboerger** 2018-04-25 07:54 UTC
