### ISSUE TITLE
I can't start the container...

### ISSUE THREAD

**Issue by nanquanyuhao** [owncloud-docker/server#65] opened 2018-06-18 04:55 UTC
```
Installing server database...
Error while trying to create admin user: An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'owncloud' AND TABLE_NAME = 'oc_appconfig'':

SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_ec_0.MAI' is read only
```

Look at see it, when I use docker-compose to start it:
```
owncloud_1  | Installing server database...
owncloud_1  | Error while trying to create admin user: An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'owncloud' AND TABLE_NAME = 'oc_appconfig'':
owncloud_1  | 
owncloud_1  | SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_ed_0.MAI' is read only
```

Can you help me?

**Comment by tboerger** [comment] 2018-06-18 06:13
Duplicate of https://github.com/owncloud-docker/server/issues/4, please use the official mariadb image and it should work.

**Closed by tboerger** 2018-06-18 06:13 UTC
