### ISSUE TITLE
I had the same problem, cause having an "not so default" installation as well and loosing the state.

### ISSUE THREAD

**Issue by wuzhefang** [owncloud-docker/server#217] opened 2021-01-12 09:10 UTC
I had the same problem, cause having an "not so default" installation as well and loosing the state.

**This is a quick fix: Just edit your .env file and rename admin to admin2. Run. Delete admin2 in admin panel and revert the .env file.**

Explanation: As correctly stated, the OCC tries to recreate the installation, and so also creating the admin user. Which already exists in the already existing installation DB and further failing to do so. Renaming it, will create admin2 with the default password, and setup/migrate your install, without touching any files, etc.. And your admin user also still has his old pw. So your installation will now have 2 admin users, where you have to remove the newly created admin2 with the admin panel.

**DO NOT FORGET to remove the admin2 with default password on upgrade/migration!**

Also relevant for: https://github.com/owncloud-docker/server/issues/101 and https://github.com/owncloud-docker/server/issues/68

_Originally posted by @sriegler in https://github.com/owncloud-docker/server/issues/104#issuecomment-479861181_

Is there better way to resolve this? No need to change the username everytime I restart it.

**Comment by frenzymind** [comment] 2021-01-29 07:47
@wuzhefang  May I ask what version "from" and "to" you upgraded ?
I have 10.2.1 Can I upgrade to 10.6  just changing tag in docker-compose file and use trick above ?

**Comment by wuzhefang** [comment] 2021-02-11 04:15
> @wuzhefang May I ask what version "from" and "to" you upgraded ?
> I have 10.2.1 Can I upgrade to 10.6 just changing tag in docker-compose file and use trick above ?

I found that, this issue is not caused by upgrade. This will happened when reinstall or restart(maybe) the owncloud-docker. 
Because it will create the `admin` user when startup auto. If I use the old database files, the `admin` user is already existed in the database, otherwise, the `admin` user could successfully created.

**Comment by Ablablab** [comment] 2021-02-28 14:21
Same issue here, I installed Owncloud a week ago and suddenly lost every user (after few days) and configuration. 
I'm on 10.6.0 Stable. 

I post my docker-compose configuration:


`version: '3.8'

volumes:
  nfs_qnap_owncloud:
    driver: local
    driver_opts:
      type: nfs
      o: addr=X.X.X.X,rw,timeo=3,rw,nolock,soft
      device: ":/Owncloud"

services:
  owncloud:
    image: owncloud/server:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db_owncloud
      - redis_owncloud
    environment:
      - OWNCLOUD_DOMAIN=mydomain.org
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=XXXXX
      - OWNCLOUD_DB_PASSWORD=XXXXX
      - OWNCLOUD_DB_HOST=db_owncloud
      - OWNCLOUD_ADMIN_USERNAME=XXXXX
      - OWNCLOUD_ADMIN_PASSWORD=XXXXX
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis_owncloud
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    extra_hosts:
      - "XXXXX:127.0.0.1"
    volumes:
      - type: volume
        source: nfs_qnap_owncloud
        target: /mnt/data
        volume:
          nocopy: true

  db_owncloud:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=XXXXX
      - MARIADB_USERNAME=XXXXX
      - MARIADB_PASSWORD=XXXXXX
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /opt/services/owncloud/mysql:/var/lib/mysql
      - /opt/services/owncloud/backup:/var/lib/backup

  redis_owncloud:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /opt/services/owncloud/redis:/var/lib/redis`

**Comment by xoxys** [comment] 2021-11-19 09:04
Hi, over the last few months, we have upgraded several Docker setups from different versions back to 10.5 on our own. We have also tried to reproduce this issue with different combinations. Since we were not able to reproduce this problem, I am closing this it for now. If you still have the issue, feel free to submit a new one.

**Closed by xoxys** 2021-11-19 09:04 UTC

**Comment by skavadias** [comment] 2022-01-21 13:43
I believe the problem is that in `mariadb`, in database `owncloud` in table `oc_users` (where 'oc_' is the tableprefix) the user 'admin' already exists. So, running --somehow (e.g., with `docker exec container_name`)-- on `mariadb` the command
`DELETE FROM owncloud.oc_users WHERE uid='admin';`
will fix it, the next time. But, I guess, you'll have to stop the restarting container for service owncloud first, so it does not issue commands to `mariadb` at the same time.

_I haven't verified this with docker and owncloud_, because I I encountered the problem with nextcloud re-installation.

I hope this helps anyone still having this problem.
