### ISSUE TITLE
installation hangs if specifying mysql volume

### ISSUE THREAD

**Issue by arielelkin** [owncloud-docker/server#69] opened 2018-07-02 10:09 UTC
I've modified the docker-compose.yml file to specify host directories where I'd like to persist my files, mysql database, and redis. But I get this when calling `up`: 

```
$ docker-compose up
Creating network "vtests_default" with the default driver
Creating volume "vtests_owncloud_files" with local driver
Creating volume "vtests_owncloud_config" with local driver
Creating volume "vtests_redis" with local driver
Creating volume "vtests_backup" with local driver
Creating volume "vtests_mysql" with local driver
Creating vtests_db_1
Creating vtests_redis_1
Creating vtests_owncloud_1
Attaching to vtests_db_1, vtests_redis_1, vtests_owncloud_1
db_1        | Cron is enabled, launching it!
redis_1     | 12:C 02 Jul 10:06:51.659 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 12:C 02 Jul 10:06:51.659 # Redis version=4.0.9, bits=64, commit=757d0c15, modified=0, pid=12, just started
redis_1     | 12:C 02 Jul 10:06:51.659 # Configuration loaded
db_1        | 180702 10:06:51 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
redis_1     | 12:M 02 Jul 10:06:51.660 * Running mode=standalone, port=6379.
owncloud_1  | Creating volume folders...
db_1        | 180702 10:06:51 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
redis_1     | 12:M 02 Jul 10:06:51.660 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
owncloud_1  | Creating hook folders...
db_1        | 180702 10:06:52 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:52 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
redis_1     | 12:M 02 Jul 10:06:51.660 # Server initialized
redis_1     | 12:M 02 Jul 10:06:51.661 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 12:M 02 Jul 10:06:51.661 * Ready to accept connections
owncloud_1  | Waiting for MySQL...
owncloud_1  | wait-for-it: waiting 180 seconds for db:3306
db_1        | 180702 10:06:53 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:53 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:06:54 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:54 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:06:55 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:55 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:06:56 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:56 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:06:57 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:57 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:06:58 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:58 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:06:59 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:06:59 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:07:00 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:07:00 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:07:01 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:07:01 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:07:02 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:07:02 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:07:03 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:07:03 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180702 10:07:04 mysqld_safe Logging to '/var/lib/mysql/8ece89d9a708.err'.
db_1        | 180702 10:07:04 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
```

My environment:

```
$ ls -a
.			.env
..			docker-compose.yml

$ cat docker-compose.yml 
version: '2.1'

volumes:
  owncloud_files:
    driver: local
  owncloud_config:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${OWNCLOUD_FILES_DIRECTORY}:/mnt/data/files
      - ${OWNCLOUD_CONFIG_DIRECTORY}:/mnt/data/config

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${OWNCLOUD_MYSQL_DIRECTORY}:/var/lib/mysql
      - ${OWNCLOUD_MYSQL_BACKUP_DIRECTORY}:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${OWNCLOUD_REDIS}:/var/lib/redis
```

I have called `docker-compose down -v` before calling `up`

**Comment by tboerger** [comment] 2018-07-02 20:41
Looks like the mysql database doesn't come up correctly, but why this happens you can see at `${OWNCLOUD_MYSQL_DIRECTORY}/8ece89d9a708.err`.

I don't know which host system you are using or any further information, but for others it helped from time to time to use the official mysql/mariadb and redis images. If you switch to these images you won't have integrated mariadb backups and they don't provide the integrated healthcheck commands.

**Comment by arielelkin** [comment] 2018-07-03 11:00
I'm using Docker Version 17.03.0-ce-mac1 (15583)

```
$ cat 7e8ef62f1627.err 
2018-07-03 10:51:05 139700620049288 [Warning] InnoDB: Using innodb_file_format is deprecated and the parameter may be removed in future releases. See https://mariadb.com/kb/en/library/xtradbinnodb-file-format/
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Uses event mutexes
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Compressed tables use zlib 1.2.11
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Using Linux native AIO
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Number of pools: 1
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Using SSE2 crc32 instructions
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Initializing buffer pool, total size = 16M, instances = 1, chunk size = 16M
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Completed initialization of buffer pool
2018-07-03 10:51:05 139700520839912 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-07-03 10:51:05 139700620049288 [ERROR] InnoDB: The Auto-extending innodb_system data file '/var/lib/mysql/ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 640 pages, max 0 (relevant if non-zero) pages!
2018-07-03 10:51:05 139700620049288 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2018-07-03 10:51:05 139700620049288 [Note] InnoDB: Starting shutdown...
2018-07-03 10:51:06 139700620049288 [ERROR] Plugin 'InnoDB' init function returned error.
2018-07-03 10:51:06 139700620049288 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2018-07-03 10:51:06 139700620049288 [Note] Plugin 'FEEDBACK' is disabled.
2018-07-03 10:51:06 139700620049288 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2018-07-03 10:51:06 139700620049288 [ERROR] Unknown/unsupported storage engine: InnoDB
2018-07-03 10:51:06 139700620049288 [ERROR] Aborting
```

I don't see why it is producing this error... You should be able to reproduce it if you specify volumes on the host for the redis and mysql containers, like I did.

**Comment by tboerger** [comment] 2018-07-03 11:20
I'm using these images on a daily base, also with host volumes, without any issue. So far I'm not able to reproduce this issue.

**Comment by arielelkin** [comment] 2018-07-03 11:36
Are you able to reproduce it thus?

```
$ pwd && ls -a
/Users/Username/vtests
.			.env
..			docker-compose.yml

$ cat .env 
OWNCLOUD_VERSION=10.0
OWNCLOUD_DOMAIN=localhost
ADMIN_USERNAME=admin
ADMIN_PASSWORD=password
HTTP_PORT=80
HTTPS_PORT=443
OWNCLOUD_FILES_DIRECTORY=/Users/Username/vtests/owncloud_files/
OWNCLOUD_CONFIG_DIRECTORY=/Users/Username/vtests/owncloud_config/
OWNCLOUD_MYSQL_DIRECTORY=/Users/Username/vtests/owncloud_mysql
OWNCLOUD_MYSQL_BACKUP_DIRECTORY=/Users/Username/vtests/owncloud_mysql_backup
OWNCLOUD_REDIS=/Users/Username/vtests/owncloud_redis

$ cat docker-compose.yml 
version: '2.1'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${OWNCLOUD_FILES_DIRECTORY}:/mnt/data/files
      - ${OWNCLOUD_CONFIG_DIRECTORY}:/mnt/data/config

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${OWNCLOUD_MYSQL_DIRECTORY}:/var/lib/mysql
      - ${OWNCLOUD_MYSQL_BACKUP_DIRECTORY}:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${OWNCLOUD_REDIS}:/var/lib/redis

$ docker-compose up
Creating network "vtests_default" with the default driver
Creating volume "vtests_files" with local driver
Creating volume "vtests_redis" with local driver
Creating volume "vtests_backup" with local driver
Creating volume "vtests_mysql" with local driver
Creating vtests_redis_1
Creating vtests_db_1
Creating vtests_owncloud_1
Attaching to vtests_redis_1, vtests_db_1, vtests_owncloud_1
db_1        | Cron is enabled, launching it!
redis_1     | 12:C 03 Jul 11:32:25.915 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 12:C 03 Jul 11:32:25.915 # Redis version=4.0.9, bits=64, commit=757d0c15, modified=0, pid=12, just started
redis_1     | 12:C 03 Jul 11:32:25.915 # Configuration loaded
owncloud_1  | Creating volume folders...
db_1        | Running mysql_install_db...
redis_1     | 12:M 03 Jul 11:32:25.916 * Running mode=standalone, port=6379.
owncloud_1  | Creating hook folders...
redis_1     | 12:M 03 Jul 11:32:25.917 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
db_1        | Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
redis_1     | 12:M 03 Jul 11:32:25.917 # Server initialized
owncloud_1  | Waiting for MySQL...
db_1        | 2018-07-03 11:32:26 140167121218440 [Warning] InnoDB: Using innodb_file_format is deprecated and the parameter may be removed in future releases. See https://mariadb.com/kb/en/library/xtradbinnodb-file-format/
redis_1     | 12:M 03 Jul 11:32:25.917 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 12:M 03 Jul 11:32:25.917 * Ready to accept connections
db_1        | 2018-07-03 11:32:26 140167121218440 [ERROR] InnoDB: preallocating 10485760 bytes for file /var/lib/mysql/ibdata1 failed with error 95
db_1        | 2018-07-03 11:32:26 140167121218440 [ERROR] InnoDB: Could not set the file size of '/var/lib/mysql/ibdata1'. Probably out of disk space
db_1        | 2018-07-03 11:32:26 140167121218440 [ERROR] InnoDB: Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
db_1        | 2018-07-03 11:32:26 140167121218440 [ERROR] Plugin 'InnoDB' init function returned error.
owncloud_1  | wait-for-it: waiting 180 seconds for db:3306
db_1        | 2018-07-03 11:32:26 140167121218440 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1        | 2018-07-03 11:32:26 140167121218440 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1        | 2018-07-03 11:32:26 140167121218440 [ERROR] Aborting
db_1        | 
db_1        | cat: write error: Broken pipe
db_1        | cat: write error: Broken pipe
db_1        | cat: write error: Broken pipe
db_1        | 
db_1        | Installation of system tables failed!  Examine the logs in
db_1        | /var/lib/mysql for more information.
db_1        | 
db_1        | The problem could be conflicting information in an external
db_1        | my.cnf files. You can ignore these by doing:
db_1        | 
db_1        |     shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
db_1        | 
db_1        | You can also try to start the mysqld daemon with:
db_1        | 
db_1        |     shell> /usr/bin/mysqld --skip-grant-tables --general-log &
db_1        | 
db_1        | and use the command line tool /usr/bin/mysql
db_1        | to connect to the mysql database and look at the grant tables:
db_1        | 
db_1        |     shell> /usr/bin/mysql -u root mysql
db_1        |     mysql> show tables;
db_1        | 
db_1        | Try 'mysqld --help' if you have problems with paths.  Using
db_1        | --general-log gives you a log in /var/lib/mysql that may be helpful.
db_1        | 
db_1        | The latest information about mysql_install_db is available at
db_1        | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
db_1        | You can find the latest source at https://downloads.mariadb.org and
db_1        | the maria-discuss email list at https://launchpad.net/~maria-discuss
db_1        | 
db_1        | Please check all of the above before submitting a bug report
db_1        | at http://mariadb.org/jira
db_1        | 
db_1        | Finished mysql_install_db
db_1        | 180703 11:32:27 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:27 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180703 11:32:28 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:28 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180703 11:32:29 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:29 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180703 11:32:30 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:30 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180703 11:32:31 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:31 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180703 11:32:32 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:32 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180703 11:32:33 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:33 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
db_1        | 180703 11:32:34 mysqld_safe Logging to '/var/lib/mysql/6d4791675ea2.err'.
db_1        | 180703 11:32:34 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
```

**Comment by tboerger** [comment] 2018-07-03 19:46
> Probably out of disk space

Please find the issue of the database via Google, or use the official mariadb/mysql image. This docker-compose config is just a reference and you can freely edit it.

**Comment by tboerger** [comment] 2018-07-03 19:47
Closing this issue for now as it's not an issue with the owncloud container.

**Closed by tboerger** 2018-07-03 19:47 UTC

**Comment by arielelkin** [comment] 2018-07-04 21:30
True, it's an issue with the mariadb container if you run it on macOS: https://github.com/wodby/docker4drupal/issues/244#issuecomment-384183414
