### ISSUE TITLE
Failed to create admin account

### ISSUE THREAD

**Issue by stlnkm** [owncloud-docker/server#27] opened 2017-11-20 17:52 UTC
A few days ago, I have successfully setup 10.0.3 oc docker with latest official mariadb docker and latest offical redis docker, but failed today. But it works in oc docker version 10.0.2. 

Everything is clean, I remove all containers, all images, and all docker data volumes.

> owncloud_1  | wait-for-it: db:3306 is available after 9 seconds
owncloud_1  | Removing custom folder...
owncloud_1  | Linking custom folder...
owncloud_1  | Removing config folder...
owncloud_1  | Linking config folder...
owncloud_1  | Copying config file...
owncloud_1  | Copying domains file...
owncloud_1  | Copying db file...
owncloud_1  | Copying utf8mb4 config...
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Installing server database...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  | Error while trying to create admin user: An exception occurred while executing 'ALTER TABLE oc_calendarsubscriptions CHANGE `lastmodified` lastmodified INT UNSIGNED DEFAULT NULL NOT NULL':
owncloud_1  |
owncloud_1  | SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'lastmodified'
owncloud_1  |  ->
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
owncloud_1  |
owncloud_1  | Type dpkg --help for help about installing and deinstalling packages [*];
owncloud_1  | Use 'apt' or 'aptitude' for user-friendly package management;
owncloud_1  | Type dpkg -Dhelp for a list of dpkg debug flag values;
owncloud_1  | Type dpkg --force-help for a list of forcing options;
owncloud_1  | Type dpkg-deb --help for help about manipulating *.deb files;
owncloud_1  |
owncloud_1  | Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
owncloud_1  | Enabling files_external app...
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
owncloud_1  |
owncloud_1  | Type dpkg --help for help about installing and deinstalling packages [*];
owncloud_1  | Use 'apt' or 'aptitude' for user-friendly package management;
owncloud_1  | Type dpkg -Dhelp for a list of dpkg debug flag values;
owncloud_1  | Type dpkg --force-help for a list of forcing options;
owncloud_1  | Type dpkg-deb --help for help about manipulating *.deb files;

**Comment by tboerger** [comment] 2017-11-21 08:44
I can't reproduce that, maybe you still left the database? Otherwise this is nothing I can clearly fix within the docker container.

**Comment by stlnkm** [comment] 2017-11-21 18:32
I exec into mariadb container and run cmd below and got same error.

> ALTER TABLE oc_calendarsubscriptions CHANGE `lastmodified` lastmodified INT UNSIGNED DEFAULT NULL NOT NULL

![image](https://user-images.githubusercontent.com/1908920/33090000-69536bba-cf2d-11e7-8f86-ddf90cb4a37a.png)

![image](https://user-images.githubusercontent.com/1908920/33089884-016e93d0-cf2d-11e7-8da9-a9ea7b4f779a.png)

**Comment by stlnkm** [comment] 2017-11-21 18:45
@tboerger Need I provide the database? How can I send it to you?

**Comment by tboerger** [comment] 2017-11-21 18:51
@deepdiver1975 is this a core issue?

**Comment by DeepDiver1975** [comment] 2017-11-22 06:40
Yes. Known core issue with mariadb 10.2. 
Will be fixed with OC 10.0.4.
Meanwhile use a lower mariadb version

**Closed by DeepDiver1975** 2017-11-22 06:40 UTC

**Comment by stlnkm** [comment] 2017-11-22 17:07
Thanks! I try mariadb 10.1.29/10.1.28/10.0.33/10.0.32/5.5.58 with owncloud 10.0.3, but got another error. And mariadb 10.2.10 with owncloud 10.0.2 work.

![image](https://user-images.githubusercontent.com/1908920/33134505-de3d29c2-cfda-11e7-9353-1862a3db4f0c.png)
