### ISSUE TITLE
Dropped docker-compose.yaml

### ISSUE THREAD

**Issue by jacekplocharczyk** [owncloud-docker/server#142] opened 2019-07-30 13:24 UTC
Hi,
I'm trying to create docker image with owncloud. In the documentation there is an information about docker-compose.yaml file which was recently deleted with the part of description in the README file. 
Could you tell me what was the reason of that? Should I not use this image?

Thanks!
Jacek

**Comment by tboerger** [comment] 2019-07-30 13:57
Duplicate of https://github.com/owncloud-docker/server/issues/141

**Closed by tboerger** 2019-07-30 13:57 UTC
